// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: indexing_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InfoResponse returns oracle information
type InfoResponse struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Network                        string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Height                         uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	TweaksOnly                     bool                   `protobuf:"varint,3,opt,name=tweaks_only,json=tweaksOnly,proto3" json:"tweaks_only,omitempty"`
	TweaksFullBasic                bool                   `protobuf:"varint,4,opt,name=tweaks_full_basic,json=tweaksFullBasic,proto3" json:"tweaks_full_basic,omitempty"`
	TweaksFullWithDustFilter       bool                   `protobuf:"varint,5,opt,name=tweaks_full_with_dust_filter,json=tweaksFullWithDustFilter,proto3" json:"tweaks_full_with_dust_filter,omitempty"`
	TweaksCutThroughWithDustFilter bool                   `protobuf:"varint,6,opt,name=tweaks_cut_through_with_dust_filter,json=tweaksCutThroughWithDustFilter,proto3" json:"tweaks_cut_through_with_dust_filter,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_indexing_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{0}
}

func (x *InfoResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *InfoResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *InfoResponse) GetTweaksOnly() bool {
	if x != nil {
		return x.TweaksOnly
	}
	return false
}

func (x *InfoResponse) GetTweaksFullBasic() bool {
	if x != nil {
		return x.TweaksFullBasic
	}
	return false
}

func (x *InfoResponse) GetTweaksFullWithDustFilter() bool {
	if x != nil {
		return x.TweaksFullWithDustFilter
	}
	return false
}

func (x *InfoResponse) GetTweaksCutThroughWithDustFilter() bool {
	if x != nil {
		return x.TweaksCutThroughWithDustFilter
	}
	return false
}

// BlockIdentifier contains block hash and height information
type BlockIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"` // 32 bytes
	BlockHeight   uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockIdentifier) Reset() {
	*x = BlockIdentifier{}
	mi := &file_indexing_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIdentifier) ProtoMessage() {}

func (x *BlockIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIdentifier.ProtoReflect.Descriptor instead.
func (*BlockIdentifier) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{1}
}

func (x *BlockIdentifier) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockIdentifier) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// BlockHeightRequest requests data for a specific block height
type BlockHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeightRequest) Reset() {
	*x = BlockHeightRequest{}
	mi := &file_indexing_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeightRequest) ProtoMessage() {}

func (x *BlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeightRequest.ProtoReflect.Descriptor instead.
func (*BlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{2}
}

func (x *BlockHeightRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// BlockHeightResponse returns block height information
type BlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeightResponse) Reset() {
	*x = BlockHeightResponse{}
	mi := &file_indexing_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeightResponse) ProtoMessage() {}

func (x *BlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeightResponse.ProtoReflect.Descriptor instead.
func (*BlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{3}
}

func (x *BlockHeightResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// BlockHashResponse returns block hash information
type BlockHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"` // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHashResponse) Reset() {
	*x = BlockHashResponse{}
	mi := &file_indexing_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHashResponse) ProtoMessage() {}

func (x *BlockHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHashResponse.ProtoReflect.Descriptor instead.
func (*BlockHashResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{4}
}

func (x *BlockHashResponse) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// IndexResponse is a generic response for any array of bytes with block identifier
type IndexResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockIdentifier *BlockIdentifier       `protobuf:"bytes,1,opt,name=block_identifier,json=blockIdentifier,proto3" json:"block_identifier,omitempty"`
	Index           []byte                 `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"` // Array of bytes (size depends on endpoint: 33-byte tweaks, 8-byte pubkeys, etc.)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_indexing_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{5}
}

func (x *IndexResponse) GetBlockIdentifier() *BlockIdentifier {
	if x != nil {
		return x.BlockIdentifier
	}
	return nil
}

func (x *IndexResponse) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

// UTXOItem represents a UTXO item as used in HTTP responses
type UTXOItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"` // 32 bytes
	Vout          uint32                 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // 32 bytes (x-only pubkey)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTXOItem) Reset() {
	*x = UTXOItem{}
	mi := &file_indexing_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXOItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOItem) ProtoMessage() {}

func (x *UTXOItem) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOItem.ProtoReflect.Descriptor instead.
func (*UTXOItem) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{6}
}

func (x *UTXOItem) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *UTXOItem) GetVout() uint32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *UTXOItem) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UTXOItem) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

// UTXOItemLight represents a lightweight UTXO item (without txid)
type UTXOItemLight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vout          uint32                 `protobuf:"varint,1,opt,name=vout,proto3" json:"vout,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // 32 bytes (x-only pubkey)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTXOItemLight) Reset() {
	*x = UTXOItemLight{}
	mi := &file_indexing_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXOItemLight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOItemLight) ProtoMessage() {}

func (x *UTXOItemLight) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOItemLight.ProtoReflect.Descriptor instead.
func (*UTXOItemLight) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{7}
}

func (x *UTXOItemLight) GetVout() uint32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *UTXOItemLight) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UTXOItemLight) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type BlockScanDataShortResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockIdentifier *BlockIdentifier       `protobuf:"bytes,1,opt,name=block_identifier,json=blockIdentifier,proto3" json:"block_identifier,omitempty"`
	CompIndex       []*ComputeIndexTxItem  `protobuf:"bytes,2,rep,name=comp_index,json=compIndex,proto3" json:"comp_index,omitempty"`
	SpentOutputs    []byte                 `protobuf:"bytes,3,opt,name=spent_outputs,json=spentOutputs,proto3" json:"spent_outputs,omitempty"` // contiguous 8 byte arrays
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockScanDataShortResponse) Reset() {
	*x = BlockScanDataShortResponse{}
	mi := &file_indexing_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockScanDataShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockScanDataShortResponse) ProtoMessage() {}

func (x *BlockScanDataShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockScanDataShortResponse.ProtoReflect.Descriptor instead.
func (*BlockScanDataShortResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{8}
}

func (x *BlockScanDataShortResponse) GetBlockIdentifier() *BlockIdentifier {
	if x != nil {
		return x.BlockIdentifier
	}
	return nil
}

func (x *BlockScanDataShortResponse) GetCompIndex() []*ComputeIndexTxItem {
	if x != nil {
		return x.CompIndex
	}
	return nil
}

func (x *BlockScanDataShortResponse) GetSpentOutputs() []byte {
	if x != nil {
		return x.SpentOutputs
	}
	return nil
}

// ComputeIndexResponse returns a compact transaction index with tweak mappings
type ComputeIndexResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockIdentifier *BlockIdentifier       `protobuf:"bytes,1,opt,name=block_identifier,json=blockIdentifier,proto3" json:"block_identifier,omitempty"`
	Index           []*ComputeIndexTxItem  `protobuf:"bytes,2,rep,name=index,proto3" json:"index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputeIndexResponse) Reset() {
	*x = ComputeIndexResponse{}
	mi := &file_indexing_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIndexResponse) ProtoMessage() {}

func (x *ComputeIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeIndexResponse.ProtoReflect.Descriptor instead.
func (*ComputeIndexResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{9}
}

func (x *ComputeIndexResponse) GetBlockIdentifier() *BlockIdentifier {
	if x != nil {
		return x.BlockIdentifier
	}
	return nil
}

func (x *ComputeIndexResponse) GetIndex() []*ComputeIndexTxItem {
	if x != nil {
		return x.Index
	}
	return nil
}

// ComputeIndexTxItem contains compact information to probe if a txid could have an interesting new output
type ComputeIndexTxItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`                                     // 32 bytes
	Tweak         []byte                 `protobuf:"bytes,2,opt,name=tweak,proto3" json:"tweak,omitempty"`                                   // 33 bytes
	OutputsShort  []byte                 `protobuf:"bytes,3,opt,name=outputs_short,json=outputsShort,proto3" json:"outputs_short,omitempty"` // Array of 8-byte shortened pubkeys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeIndexTxItem) Reset() {
	*x = ComputeIndexTxItem{}
	mi := &file_indexing_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIndexTxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIndexTxItem) ProtoMessage() {}

func (x *ComputeIndexTxItem) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeIndexTxItem.ProtoReflect.Descriptor instead.
func (*ComputeIndexTxItem) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{10}
}

func (x *ComputeIndexTxItem) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *ComputeIndexTxItem) GetTweak() []byte {
	if x != nil {
		return x.Tweak
	}
	return nil
}

func (x *ComputeIndexTxItem) GetOutputsShort() []byte {
	if x != nil {
		return x.OutputsShort
	}
	return nil
}

// FullTxItem contains complete transaction information for Full Block endpoint
type FullTxItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`     // 32 bytes
	Tweak         []byte                 `protobuf:"bytes,2,opt,name=tweak,proto3" json:"tweak,omitempty"`   // 33 bytes
	Inputs        []byte                 `protobuf:"bytes,3,opt,name=inputs,proto3" json:"inputs,omitempty"` // Array of 36-byte outpoints
	Utxos         []*UTXOItemLight       `protobuf:"bytes,4,rep,name=utxos,proto3" json:"utxos,omitempty"`   // Array of lightweight UTXO items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullTxItem) Reset() {
	*x = FullTxItem{}
	mi := &file_indexing_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullTxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullTxItem) ProtoMessage() {}

func (x *FullTxItem) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullTxItem.ProtoReflect.Descriptor instead.
func (*FullTxItem) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{11}
}

func (x *FullTxItem) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *FullTxItem) GetTweak() []byte {
	if x != nil {
		return x.Tweak
	}
	return nil
}

func (x *FullTxItem) GetInputs() []byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *FullTxItem) GetUtxos() []*UTXOItemLight {
	if x != nil {
		return x.Utxos
	}
	return nil
}

// FullBlockResponse returns complete block data with all transaction details
type FullBlockResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockIdentifier *BlockIdentifier       `protobuf:"bytes,1,opt,name=block_identifier,json=blockIdentifier,proto3" json:"block_identifier,omitempty"`
	Index           []*FullTxItem          `protobuf:"bytes,2,rep,name=index,proto3" json:"index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FullBlockResponse) Reset() {
	*x = FullBlockResponse{}
	mi := &file_indexing_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullBlockResponse) ProtoMessage() {}

func (x *FullBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullBlockResponse.ProtoReflect.Descriptor instead.
func (*FullBlockResponse) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{12}
}

func (x *FullBlockResponse) GetBlockIdentifier() *BlockIdentifier {
	if x != nil {
		return x.BlockIdentifier
	}
	return nil
}

func (x *FullBlockResponse) GetIndex() []*FullTxItem {
	if x != nil {
		return x.Index
	}
	return nil
}

// RangedBlockHeightRequestFiltered requests filtered data for a range of block heights
type RangedBlockHeightRequestFiltered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Dustlimit     uint64                 `protobuf:"varint,3,opt,name=dustlimit,proto3" json:"dustlimit,omitempty"`
	CutThrough    bool                   `protobuf:"varint,4,opt,name=cut_through,json=cutThrough,proto3" json:"cut_through,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangedBlockHeightRequestFiltered) Reset() {
	*x = RangedBlockHeightRequestFiltered{}
	mi := &file_indexing_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangedBlockHeightRequestFiltered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangedBlockHeightRequestFiltered) ProtoMessage() {}

func (x *RangedBlockHeightRequestFiltered) ProtoReflect() protoreflect.Message {
	mi := &file_indexing_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangedBlockHeightRequestFiltered.ProtoReflect.Descriptor instead.
func (*RangedBlockHeightRequestFiltered) Descriptor() ([]byte, []int) {
	return file_indexing_server_proto_rawDescGZIP(), []int{13}
}

func (x *RangedBlockHeightRequestFiltered) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *RangedBlockHeightRequestFiltered) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *RangedBlockHeightRequestFiltered) GetDustlimit() uint64 {
	if x != nil {
		return x.Dustlimit
	}
	return 0
}

func (x *RangedBlockHeightRequestFiltered) GetCutThrough() bool {
	if x != nil {
		return x.CutThrough
	}
	return false
}

var File_indexing_server_proto protoreflect.FileDescriptor

const file_indexing_server_proto_rawDesc = "" +
	"\n" +
	"\x15indexing_server.proto\x12\x12blindbit.oracle.v1\"\x9a\x02\n" +
	"\fInfoResponse\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x1f\n" +
	"\vtweaks_only\x18\x03 \x01(\bR\n" +
	"tweaksOnly\x12*\n" +
	"\x11tweaks_full_basic\x18\x04 \x01(\bR\x0ftweaksFullBasic\x12>\n" +
	"\x1ctweaks_full_with_dust_filter\x18\x05 \x01(\bR\x18tweaksFullWithDustFilter\x12K\n" +
	"#tweaks_cut_through_with_dust_filter\x18\x06 \x01(\bR\x1etweaksCutThroughWithDustFilter\"S\n" +
	"\x0fBlockIdentifier\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\"7\n" +
	"\x12BlockHeightRequest\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\"8\n" +
	"\x13BlockHeightResponse\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\"2\n" +
	"\x11BlockHashResponse\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\"u\n" +
	"\rIndexResponse\x12N\n" +
	"\x10block_identifier\x18\x01 \x01(\v2#.blindbit.oracle.v1.BlockIdentifierR\x0fblockIdentifier\x12\x14\n" +
	"\x05index\x18\x02 \x01(\fR\x05index\"b\n" +
	"\bUTXOItem\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\rR\x04vout\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06pubkey\x18\x04 \x01(\fR\x06pubkey\"S\n" +
	"\rUTXOItemLight\x12\x12\n" +
	"\x04vout\x18\x01 \x01(\rR\x04vout\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06pubkey\x18\x03 \x01(\fR\x06pubkey\"\xd8\x01\n" +
	"\x1aBlockScanDataShortResponse\x12N\n" +
	"\x10block_identifier\x18\x01 \x01(\v2#.blindbit.oracle.v1.BlockIdentifierR\x0fblockIdentifier\x12E\n" +
	"\n" +
	"comp_index\x18\x02 \x03(\v2&.blindbit.oracle.v1.ComputeIndexTxItemR\tcompIndex\x12#\n" +
	"\rspent_outputs\x18\x03 \x01(\fR\fspentOutputs\"\xa4\x01\n" +
	"\x14ComputeIndexResponse\x12N\n" +
	"\x10block_identifier\x18\x01 \x01(\v2#.blindbit.oracle.v1.BlockIdentifierR\x0fblockIdentifier\x12<\n" +
	"\x05index\x18\x02 \x03(\v2&.blindbit.oracle.v1.ComputeIndexTxItemR\x05index\"c\n" +
	"\x12ComputeIndexTxItem\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x14\n" +
	"\x05tweak\x18\x02 \x01(\fR\x05tweak\x12#\n" +
	"\routputs_short\x18\x03 \x01(\fR\foutputsShort\"\x87\x01\n" +
	"\n" +
	"FullTxItem\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x14\n" +
	"\x05tweak\x18\x02 \x01(\fR\x05tweak\x12\x16\n" +
	"\x06inputs\x18\x03 \x01(\fR\x06inputs\x127\n" +
	"\x05utxos\x18\x04 \x03(\v2!.blindbit.oracle.v1.UTXOItemLightR\x05utxos\"\x99\x01\n" +
	"\x11FullBlockResponse\x12N\n" +
	"\x10block_identifier\x18\x01 \x01(\v2#.blindbit.oracle.v1.BlockIdentifierR\x0fblockIdentifier\x124\n" +
	"\x05index\x18\x02 \x03(\v2\x1e.blindbit.oracle.v1.FullTxItemR\x05index\"\x89\x01\n" +
	" RangedBlockHeightRequestFiltered\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\x12\x1c\n" +
	"\tdustlimit\x18\x03 \x01(\x04R\tdustlimit\x12\x1f\n" +
	"\vcut_through\x18\x04 \x01(\bR\n" +
	"cutThroughB\x06Z\x04./pbb\x06proto3"

var (
	file_indexing_server_proto_rawDescOnce sync.Once
	file_indexing_server_proto_rawDescData []byte
)

func file_indexing_server_proto_rawDescGZIP() []byte {
	file_indexing_server_proto_rawDescOnce.Do(func() {
		file_indexing_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexing_server_proto_rawDesc), len(file_indexing_server_proto_rawDesc)))
	})
	return file_indexing_server_proto_rawDescData
}

var file_indexing_server_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_indexing_server_proto_goTypes = []any{
	(*InfoResponse)(nil),                     // 0: blindbit.oracle.v1.InfoResponse
	(*BlockIdentifier)(nil),                  // 1: blindbit.oracle.v1.BlockIdentifier
	(*BlockHeightRequest)(nil),               // 2: blindbit.oracle.v1.BlockHeightRequest
	(*BlockHeightResponse)(nil),              // 3: blindbit.oracle.v1.BlockHeightResponse
	(*BlockHashResponse)(nil),                // 4: blindbit.oracle.v1.BlockHashResponse
	(*IndexResponse)(nil),                    // 5: blindbit.oracle.v1.IndexResponse
	(*UTXOItem)(nil),                         // 6: blindbit.oracle.v1.UTXOItem
	(*UTXOItemLight)(nil),                    // 7: blindbit.oracle.v1.UTXOItemLight
	(*BlockScanDataShortResponse)(nil),       // 8: blindbit.oracle.v1.BlockScanDataShortResponse
	(*ComputeIndexResponse)(nil),             // 9: blindbit.oracle.v1.ComputeIndexResponse
	(*ComputeIndexTxItem)(nil),               // 10: blindbit.oracle.v1.ComputeIndexTxItem
	(*FullTxItem)(nil),                       // 11: blindbit.oracle.v1.FullTxItem
	(*FullBlockResponse)(nil),                // 12: blindbit.oracle.v1.FullBlockResponse
	(*RangedBlockHeightRequestFiltered)(nil), // 13: blindbit.oracle.v1.RangedBlockHeightRequestFiltered
}
var file_indexing_server_proto_depIdxs = []int32{
	1,  // 0: blindbit.oracle.v1.IndexResponse.block_identifier:type_name -> blindbit.oracle.v1.BlockIdentifier
	1,  // 1: blindbit.oracle.v1.BlockScanDataShortResponse.block_identifier:type_name -> blindbit.oracle.v1.BlockIdentifier
	10, // 2: blindbit.oracle.v1.BlockScanDataShortResponse.comp_index:type_name -> blindbit.oracle.v1.ComputeIndexTxItem
	1,  // 3: blindbit.oracle.v1.ComputeIndexResponse.block_identifier:type_name -> blindbit.oracle.v1.BlockIdentifier
	10, // 4: blindbit.oracle.v1.ComputeIndexResponse.index:type_name -> blindbit.oracle.v1.ComputeIndexTxItem
	7,  // 5: blindbit.oracle.v1.FullTxItem.utxos:type_name -> blindbit.oracle.v1.UTXOItemLight
	1,  // 6: blindbit.oracle.v1.FullBlockResponse.block_identifier:type_name -> blindbit.oracle.v1.BlockIdentifier
	11, // 7: blindbit.oracle.v1.FullBlockResponse.index:type_name -> blindbit.oracle.v1.FullTxItem
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_indexing_server_proto_init() }
func file_indexing_server_proto_init() {
	if File_indexing_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexing_server_proto_rawDesc), len(file_indexing_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indexing_server_proto_goTypes,
		DependencyIndexes: file_indexing_server_proto_depIdxs,
		MessageInfos:      file_indexing_server_proto_msgTypes,
	}.Build()
	File_indexing_server_proto = out.File
	file_indexing_server_proto_goTypes = nil
	file_indexing_server_proto_depIdxs = nil
}
