// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: oracle_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_oracle_service_proto protoreflect.FileDescriptor

const file_oracle_service_proto_rawDesc = "" +
	"\n" +
	"\x14oracle_service.proto\x12\x12blindbit.oracle.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15indexing_server.proto2\xd1\x05\n" +
	"\rOracleService\x12C\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a .blindbit.oracle.v1.InfoResponse\x12U\n" +
	"\x12GetBestBlockHeight\x12\x16.google.protobuf.Empty\x1a'.blindbit.oracle.v1.BlockHeightResponse\x12e\n" +
	"\x14GetBlockHashByHeight\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a%.blindbit.oracle.v1.BlockHashResponse\x12\x82\x01\n" +
	"\x18StreamBlockScanDataShort\x124.blindbit.oracle.v1.RangedBlockHeightRequestFiltered\x1a..blindbit.oracle.v1.BlockScanDataShortResponse0\x01\x12v\n" +
	"\x12StreamComputeIndex\x124.blindbit.oracle.v1.RangedBlockHeightRequestFiltered\x1a(.blindbit.oracle.v1.ComputeIndexResponse0\x01\x12]\n" +
	"\fGetFullBlock\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a%.blindbit.oracle.v1.FullBlockResponse\x12a\n" +
	"\x14GetSpentOutputsShort\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a!.blindbit.oracle.v1.IndexResponseB\x06Z\x04./pbb\x06proto3"

var file_oracle_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                    // 0: google.protobuf.Empty
	(*BlockHeightRequest)(nil),               // 1: blindbit.oracle.v1.BlockHeightRequest
	(*RangedBlockHeightRequestFiltered)(nil), // 2: blindbit.oracle.v1.RangedBlockHeightRequestFiltered
	(*InfoResponse)(nil),                     // 3: blindbit.oracle.v1.InfoResponse
	(*BlockHeightResponse)(nil),              // 4: blindbit.oracle.v1.BlockHeightResponse
	(*BlockHashResponse)(nil),                // 5: blindbit.oracle.v1.BlockHashResponse
	(*BlockScanDataShortResponse)(nil),       // 6: blindbit.oracle.v1.BlockScanDataShortResponse
	(*ComputeIndexResponse)(nil),             // 7: blindbit.oracle.v1.ComputeIndexResponse
	(*FullBlockResponse)(nil),                // 8: blindbit.oracle.v1.FullBlockResponse
	(*IndexResponse)(nil),                    // 9: blindbit.oracle.v1.IndexResponse
}
var file_oracle_service_proto_depIdxs = []int32{
	0, // 0: blindbit.oracle.v1.OracleService.GetInfo:input_type -> google.protobuf.Empty
	0, // 1: blindbit.oracle.v1.OracleService.GetBestBlockHeight:input_type -> google.protobuf.Empty
	1, // 2: blindbit.oracle.v1.OracleService.GetBlockHashByHeight:input_type -> blindbit.oracle.v1.BlockHeightRequest
	2, // 3: blindbit.oracle.v1.OracleService.StreamBlockScanDataShort:input_type -> blindbit.oracle.v1.RangedBlockHeightRequestFiltered
	2, // 4: blindbit.oracle.v1.OracleService.StreamComputeIndex:input_type -> blindbit.oracle.v1.RangedBlockHeightRequestFiltered
	1, // 5: blindbit.oracle.v1.OracleService.GetFullBlock:input_type -> blindbit.oracle.v1.BlockHeightRequest
	1, // 6: blindbit.oracle.v1.OracleService.GetSpentOutputsShort:input_type -> blindbit.oracle.v1.BlockHeightRequest
	3, // 7: blindbit.oracle.v1.OracleService.GetInfo:output_type -> blindbit.oracle.v1.InfoResponse
	4, // 8: blindbit.oracle.v1.OracleService.GetBestBlockHeight:output_type -> blindbit.oracle.v1.BlockHeightResponse
	5, // 9: blindbit.oracle.v1.OracleService.GetBlockHashByHeight:output_type -> blindbit.oracle.v1.BlockHashResponse
	6, // 10: blindbit.oracle.v1.OracleService.StreamBlockScanDataShort:output_type -> blindbit.oracle.v1.BlockScanDataShortResponse
	7, // 11: blindbit.oracle.v1.OracleService.StreamComputeIndex:output_type -> blindbit.oracle.v1.ComputeIndexResponse
	8, // 12: blindbit.oracle.v1.OracleService.GetFullBlock:output_type -> blindbit.oracle.v1.FullBlockResponse
	9, // 13: blindbit.oracle.v1.OracleService.GetSpentOutputsShort:output_type -> blindbit.oracle.v1.IndexResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oracle_service_proto_init() }
func file_oracle_service_proto_init() {
	if File_oracle_service_proto != nil {
		return
	}
	file_indexing_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_service_proto_rawDesc), len(file_oracle_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oracle_service_proto_goTypes,
		DependencyIndexes: file_oracle_service_proto_depIdxs,
	}.Build()
	File_oracle_service_proto = out.File
	file_oracle_service_proto_goTypes = nil
	file_oracle_service_proto_depIdxs = nil
}
